import path from 'path';

// path to code generated by the model
export const pathToCode = "/dev/shm/receivercodes/codelog.md"; 
export const logs = path.join(process.cwd(), "memo", "satateslogs", "logs.txt");
