import path from 'path';

const CWD = process.cwd();

export const MEMO_DIR = path.join(CWD, 'memo');
export const STATES_LOGS_DIR = path.join(MEMO_DIR, 'states-logs');
export const STATES_LOG_FILE = path.join(STATES_LOGS_DIR, 'logs.txt');

export const TASKS_STATE_DIR = path.join(MEMO_DIR, 'state', 'tasks');
export const TASKS_TASKS_DIR = path.join(TASKS_STATE_DIR, 'tasks');
export const TASKS_STATE_FILE = path.join(TASKS_STATE_DIR, 'state.json');

function resolveFromCwd(p: string): string {
  return path.isAbsolute(p) ? p : path.join(CWD, p);
}

export function getGeneratedMarkdownPath(): string {
  const fromEnv = process.env.BOXSAFE_MARKDOWN_PATH?.trim();
  if (fromEnv) return resolveFromCwd(fromEnv);
  return path.join(MEMO_DIR, 'generated', 'codelog.md');
}

export function getArtifactOutputPath(): string {
  const fromEnv = process.env.AGENT_OUTPUT_PATH?.trim();
  if (fromEnv) return resolveFromCwd(fromEnv);
  return path.join(CWD, 'out.ts');
}

// path to code generated by the model
export const pathToCode = getGeneratedMarkdownPath();

// Backwards-compatible alias
export const logs = STATES_LOG_FILE;
