import path from 'path';

const CWD = process.cwd();
const RAM_ROOT = '/dev/shm';

export const MEMO_DIR = path.join(CWD, 'memo');
export const STATES_LOGS_DIR = path.join(MEMO_DIR, 'states-logs');
export const STATES_LOG_FILE = path.join(STATES_LOGS_DIR, 'logs.txt');

export const TASKS_STATE_DIR = path.join(MEMO_DIR, 'state', 'tasks');
export const TASKS_TASKS_DIR = path.join(TASKS_STATE_DIR, 'tasks');
export const TASKS_STATE_FILE = path.join(TASKS_STATE_DIR, 'state.json');

// path to code generated by the model
export const pathToCode = path.join(RAM_ROOT, 'receivercodes', 'codelog.md');

// Backwards-compatible alias
export const logs = STATES_LOG_FILE;
